site_name: Phantom NMS
repo_url: https://github.com/nielsvanhooy/litestar-fullstack
edit_uri: ./edit/main/docs

# Sticking with readthedocs theme for basic template
# material theme also installed
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: mirage
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: mirage-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

extra_css:
  - css/extra.css

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - User Guide:
      - Installation: user_guide/installation.md
      - Usage: user_guide/usage.md
      - Email Client: user_guide/email_client.md
  - Developer Guide:
      - Developer Setup: developer_guide/developer_setup.md
      - Commands: developer_guide/commands.md
      - Workflows: developer_guide/workflows.md
      - Releases: developer_guide/releases.md
  - App Reference:
      - App Reference: app_reference/app.md
  - Code Reference:
      - Core:
          - CLI: code_reference/cli.md
          - Config: code_reference/config.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

dev_addr: "0.0.0.0:8080"
