# type: ignore
"""added foreignkey to business configuration to CPE

Revision ID: 03862a8b6450
Revises: cf1dccc9d1ed
Create Date: 2023-08-23 15:49:18.974148

"""
import warnings

import sqlalchemy as sa
from alembic import op
from litestar.contrib.sqlalchemy.types import GUID, ORA_JSONB, DateTimeUTC

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB

# revision identifiers, used by Alembic.
revision = "03862a8b6450"
down_revision = "cf1dccc9d1ed"
branch_labels = None
depends_on = None


def upgrade():
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade():
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades():
    """Schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cpe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("product_configuration_id", sa.GUID(length=16), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_cpe_product_configuration_id_product_configuration"),
            "product_configuration",
            ["product_configuration_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def schema_downgrades():
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cpe", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_cpe_product_configuration_id_product_configuration"),
            type_="foreignkey",
        )
        batch_op.drop_column("product_configuration_id")

    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
